#!/bin/bash

# Verificar si el servicio Apache2 ya está instalado
if ! systemctl is-active --quiet apache2; then
  echo "El servicio Apache2 no está instalado en este sistema."
  exit 1
fi

# Iniciar el servicio Apache2 si no está en ejecución
if ! systemctl is-active --quiet apache2; then
  sudo systemctl start apache2
  if [ $? -eq 0 ]; then
    echo "El servicio Apache2 se ha iniciado correctamente."
  else
    echo "Error al iniciar el servicio Apache2."
    exit 1
  fi
else
  echo "El servicio Apache2 ya está en ejecución."
fi
